version: "3.3"
services:
  app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
  db:
    image: "mysql:8.0.29"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ydfas67FDASdf67tgfs
    volumes:
      - "./db/init.sql:/docker-entrypoint-initdb.d/1.sql"
      - "./db/data:/var/lib/mysql"
